# STAGE: Build
FROM gradle:7.4.2-jdk11 as builder

# Create Working Directory
ENV BUILD_DIR=/home/build/
RUN mkdir $BUILD_DIR
WORKDIR $BUILD_DIR

# Download Dependencies
COPY build.gradle settings.gradle $BUILD_DIR
RUN gradle build -x test --continue

# Copy Source
COPY src src

# Build jar
RUN gradle build -x test

# Rename jar
RUN export PROJECT_NAME=$(gradle properties -q | grep "name:" | awk '{print $2}') && \
  export PROJECT_VERSION=$(gradle properties -q | grep "version:" | awk '{print $2}') && \
  cd build/libs/ && \
  mv ./${PROJECT_NAME}-${PROJECT_VERSION}.jar app.jar

# Non-Root User
ARG USERNAME=appuser
ARG GROUP=$USERNAME
ARG USER_UID=1001
ARG USER_GID=$USER_UID

# Create app directory
ENV APP_HOME=/home/app
RUN mkdir -p $APP_HOME
RUN addgroup --gid $USER_GID $GROUP
RUN adduser --uid $USER_UID --gid $USER_GID $USERNAME
WORKDIR $APP_HOME

# Copy jar file over from builder stage
RUN mv ${BUILD_DIR}/build/libs/app.jar ${APP_HOME}
RUN chown $USER_UID:$USER_GID app.jar && chmod 700 app.jar

USER $USERNAME

EXPOSE 8080

CMD exec java $JAVA_OPTS -jar ./app.jar