pipeline {
  agent none

  stages {
    // stage('Gradle Build') {
    //   agent {
    //     docker {
    //       image 'gradle:7.4.2-jdk11'
    //     }
    //   }
    //   steps {
    //     sh """
    //     #!/bin/sh
    //     cd 2-jenkins-in-docker/app
    //     gradle build -x test
    //     """
    //   }
    // }
    stage('Build Docker Image') {
      agent {
        docker {
          image 'docker:20.10.18'
          args "--entrypoint='' -v /certs/client:/certs/client"// --env DOCKER_HOST=tcp://172.18.0.2:2376 --env DOCKER_CERT_PATH=/certs/client --env DOCKER_TLS_VERIFY=1"
        }
      }
      environment {
        DOCKER_HOST = "tcp://172.18.0.2:2376"
        DOCKER_CERT_PATH = "/certs/client"
        DOCKER_TLS_VERIFY = "1"
      }
      steps {
        sh """
        #!/bin/sh
        printenv
        ls -la /certs/client
        docker images
        """
        // script {
        //   sh "printenv"
        //   def buildContextPath = "./2-jenkins-in-docker/app"
        //   def dockerfile = 'Dockerfile'
        //   def customImage = docker.build("my-image:${env.BUILD_ID}", "-f ${buildContextPath}/${dockerfile} ${buildContextPath}")
        // }
      }
    }
  }
}