pipeline {
  agent none
  environment {
    DOCKER_HOST = "tcp://${DOCKER_HOST_IP}:2376"
  }

  stages {
    // stage('Gradle Build') {
    //   agent {
    //     docker {
    //       image 'gradle:7.4.2-jdk11'
    //     }
    //   }
    //   steps {
    //     sh """
    //     #!/bin/sh
    //     cd 2-jenkins-in-docker/app
    //     gradle build -x test
    //     """
    //   }
    // }
    stage('Build Docker Image') {
      agent {
        docker {
          image 'docker:20.10.18-dind'
          args "--entrypoint='' -v /certs/client:/certs/client"
        }
      }
      steps {
        script {
          def buildContextPath = "./2-jenkins-in-docker/app"
          def dockerfile = 'Dockerfile'
          def customImage = docker.build("my-image:${env.BUILD_ID}", "-f ${buildContextPath}/${dockerfile} ${buildContextPath}")
        }
      }
    }
  }
}